# Load necessary modules
module(load="imudp")   # For receiving UDP messages
input(type="imudp" port="10514")

# TCP endpoint configuration
*.* action(
  type="omfwd" 
	target="alloy" 
	port="12345" 
	protocol="udp" 
	Template="RSYSLOG_SyslogProtocol23Format"
	)
