# Load necessary modules
module(load="imudp")   # For receiving UDP messages
input(type="imudp" port="10514")
module(load="imtcp") # For receiving TCP messages
input(type="imtcp" port="10514")

# TCP endpoint configuration
*.* action(
  type="omfwd" 
  target="alloy" 
  port="12346" 
  protocol="udp"
  Template="RSYSLOG_SyslogProtocol23Format"
)
# UDP endpoint configuration
*.* action(
  type="omfwd"
  target="alloy"
  port="12347"
  protocol="tcp"
  Template="RSYSLOG_SyslogProtocol23Format"
)
